#!/bin/bash
if [ ! -e $1 ]; then
	echo "Input file does not exist"
	exit 1;
fi

if [ -e out ]; then
	rm -r out
fi

BASE="0x$(od -A n -h -j 34 -N 2 ./$1|sed 's/ //g')0000"
CMDLINE="$(od -A n --strings -j 64 -N 512 ./$1)"

echo "Base address: $BASE"
echo "Command line: '$CMDLINE'"

mkdir out
perl split_bootimg.pl ./$1
cd out

mkdir ramdisk
cd ramdisk
gunzip -c ../../boot.img-ramdisk.gz | cpio -i
