#!/bin/sh

#create working directory variable - automatic - will detect whatever directory you extract the
#source package too
PLACE=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

cd $PLACE/$1/
echo "#!/bin/sh" > $PLACE/to_delete.sh
find . -name "*" | while read FILE ; do
        if [ -d $FILE ] ; then continue; fi ;
        diff -q $FILE $PLACE/$2/$FILE > /dev/null ;
        if [ $? = 0 ]; then echo "rm -f "$PLACE/$1/$FILE >> $PLACE/to_delete.sh; else echo $PLACE/$1/$FILE >> $PLACE/different_files; fi;
done
